name: Reveal a secret when the repository is tagged as something starting by secret

on:
  push:
    tags:
      - 'secret*'

jobs:
  reveal-secret:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        SECRET_MSG: ${{ secrets.TOP_SECRET }}
      run: |
        echo "$TOP_SECRET"
        if [ "$TOP_SECRET" = 'do not tell anyone' ]; then
          echo matches
          echo "::debug::matches"
        fi
        echo "::debug::$TOP_SECRET"
    - Print secret
      run: |
        echo something
        echo "::set-output name=secret:::$TOP_SECRET"
