name: Reveal a secret when the repository is tagged as something starting by "secret"

on:
  push:
    tags:
      - 'secret*'

jobs:
  reveal-secret:
    steps:
    - shell: bash
      env:
        SECRET_MSG: ${{ secrets.TOP_SECRET }}
      run: |
        echo "$TOP_SECRET"
